export const governorates = [
    { ar: 'الإسكندرية', en: 'Alexandria', code: 'ALX' },
    { ar: 'أسوان', en: 'Aswan', code: 'ASN' },
    { ar: 'أسيوط', en: 'Asyut', code: 'AST' },
    { ar: 'البحيرة', en: 'Beheira', code: 'BH' },
    { ar: 'بني سويف', en: 'Beni Suef', code: 'BNS' },
    { ar: 'القاهرة', en: 'Cairo', code: 'C' },
    { ar: 'الدقهلية', en: 'Dakahlia', code: 'DK' },
    { ar: 'دمياط', en: 'Damietta', code: 'DT' },
    { ar: 'الفيوم', en: 'Faiyum', code: 'FYM' },
    { ar: 'الغربية', en: 'Gharbia', code: 'GH' },
    { ar: 'الجيزة', en: 'Giza', code: 'GZ' },
    { ar: 'الإسماعيلية', en: 'Ismailia', code: 'IS' },
    { ar: 'كفر الشيخ', en: 'Kafr El Sheikh', code: 'KFS' },
    { ar: 'الأقصر', en: 'Luxor', code: 'LX' },
    { ar: 'مطروح', en: 'Matruh', code: 'MT' },
    { ar: 'المنيا', en: 'Minya', code: 'MN' },
    { ar: 'المنوفية', en: 'Monufia', code: 'MNF' },
    { ar: 'الوادي الجديد', en: 'New Valley', code: 'WAD' },
    { ar: 'شمال سيناء', en: 'North Sinai', code: 'SIN' },
    { ar: 'بورسعيد', en: 'Port Said', code: 'PTS' },
    { ar: 'القليوبية', en: 'Qalyubia', code: 'KB' },
    { ar: 'قنا', en: 'Qena', code: 'KN' },
    { ar: 'البحر الأحمر', en: 'Red Sea', code: 'BA' },
    { ar: 'الشرقية', en: 'Sharqia', code: 'SHR' },
    { ar: 'سوهج', en: 'Sohag', code: 'SHG' },
    { ar: 'جنوب سيناء', en: 'South Sinai', code: 'JS' },
    { ar: 'السويس', en: 'Suez', code: 'SUZ' }
];
