export type NfsaSupplier = {
  id: string;
  supplierName: string;
  address: string;
  governorate: string;
  activityType: string;
  phoneNumber?: string;
  notes?: string;
};

export const nfsaSuppliersData: NfsaSupplier[] = [
  { id: '1', supplierName: 'شركة الوادي للتنمية الزراعية (دالة)', address: 'الكيلو 59 - طريق مصر اسكندرية الصحراوي', governorate: 'Giza', activityType: 'محطة تعبئة خضار وفاكهة طازجة', phoneNumber: '01001114451' },
  { id: '2', supplierName: 'اجريفروست', address: 'الكيلو 54 طريق مصر اسكندرية الصحراوي', governorate: 'Giza', activityType: 'محطة تعبئة خضار وفاكهة طازجة', phoneNumber: '01225639998' },
  { id: '3', supplierName: 'اجرو ايجيبت', address: 'الكيلو 54 طريق مصر اسكندرية الصحراوي', governorate: 'Giza', activityType: 'محطة تعبئة خضار وفاكهة طازجة', phoneNumber: '01022624541' },
  { id: '4', supplierName: 'اجرو لاند', address: 'الكيلو 80 طريق مصر اسكندرية الصحراوي', governorate: 'Beheira', activityType: 'محطة تعبئة خضار وفاكهة طازجة', phoneNumber: '01013951662' },
  { id: '5', supplierName: 'اجرين', address: 'الكيلو 90 طريق مصر اسكندرية الصحراوي', governorate: 'Beheira', activityType: 'محطة تعبئة خضار وفاكهة طازجة', phoneNumber: '0123108044' },
  { id: '6', supplierName: 'الأصيل لتصدير الحاصلات الزراعية', address: 'المنصورية - مركز دراو - اسوان', governorate: 'Aswan', activityType: 'محطة تعبئة وتجهيز حاصلات زراعية', phoneNumber: '01001663138' },
  { id: '7', supplierName: 'الألمانية لفرز وتعبئة وتصدير الحاصلات الزراعية (ش.ذ.م.م)', address: 'الكيلو 6 شرق الرياح - مركز طوخ - القليوبية', governorate: 'Qalyubia', activityType: 'محطة تعبئة خضار وفاكهة طازجة', phoneNumber: '01020116886' },
  { id: '8', supplierName: 'الايمان لتصدير الحاصلات الزراعية', address: 'بلقاس - الطريق الزراعي - الدقهلية', governorate: 'Dakahlia', activityType: 'محطة تعبئة وتجهيز حاصلات زراعية', phoneNumber: '01002004862' },
  { id: '9', supplierName: 'البركة للتصدير والاستيراد', address: 'طريق جمصة المنصورة - طلخا - الدقهلية', governorate: 'Dakahlia', activityType: 'محطة تعبئة وتجهيز حاصلات زراعية', phoneNumber: '01000768398' },
  { id: '10', supplierName: 'التقوى لفرز وتعبئة وتصدير الحاصلات الزراعية', address: 'الكيلو 106 - طريق مصر الاسماعيلية الصحراوي - الشرقية', governorate: 'Sharqia', activityType: 'محطة تعبئة خضار وفاكهة طازجة', phoneNumber: '01223915007' },
  { id: '11', supplierName: 'التوحيد والنور لتصدير الحاصلات الزراعية', address: 'الكيلو 106 - طريق مصر الاسماعيلية الصحراوي - الشرقية', governorate: 'Sharqia', activityType: 'محطة تعبئة خضار وفاكهة طازجة', phoneNumber: '01110333045' },
  { id: '12', supplierName: 'الجوهري للتجارة والتوزيع', address: 'المنطقة الصناعية - جمصة - الدقهلية', governorate: 'Dakahlia', activityType: 'محطة تعبئة خضار وفاكهة طازجة', phoneNumber: '01110333045' },
  { id: '13', supplierName: 'الدقهلية لتصدير وتجميد الحاصلات الزراعية (شركة مساهمة مصرية)', address: 'جمصة - المنطقة الصناعية', governorate: 'Dakahlia', activityType: 'محطة تعبئة خضار وفاكهة طازجة', phoneNumber: '01223468852' },
  { id: '14', supplierName: 'الدولية لتصدير الحاصلات الزراعية', address: 'جمصة - المنطقة الصناعية', governorate: 'Dakahlia', activityType: 'محطة تعبئة خضار وفاكهة طازجة', phoneNumber: '04/ 53118880' },
  { id: '15', supplierName: 'الرواد لتصدير الحاصلات الزراعية', address: 'المنطقة الصناعية الثانية - مدينة السادات - المنوفية', governorate: 'Monufia', activityType: 'محطة تعبئة وتجهيز حاصلات زراعية', phoneNumber: '01159795500' },
  { id: '16', supplierName: 'الرواد لفرز وتعبئة وتصدير الحاصلات الزراعية', address: 'المنطقة الصناعية - قطعة 726 - مدينة السادات - المنوفية', governorate: 'Monufia', activityType: 'محطة تعبئة خضار وفاكهة طازجة', phoneNumber: '01001670669' },
  { id: '17', supplierName: 'الريان لتصدير وتجميد الحاصلات الزراعية', address: 'العاشر من رمضان - الشرقية', governorate: 'Sharqia', activityType: 'محطة تعبئة وتجهيز حاصلات زراعية', phoneNumber: '01274834020' },
  { id: '18', supplierName: 'السلام للتجارة والتوزيع', address: 'المنطقة الصناعية - قويسنا - المنوفية', governorate: 'Monufia', activityType: 'محطة تعبئة خضار وفاكهة طازجة', phoneNumber: '01000387343' },
  { id: '19', supplierName: 'السلام لتصدير الحاصلات الزراعية', address: 'طريق مصر/اسماعيلية الصحراوي - مدينة السلام', governorate: 'Cairo', activityType: 'محطة تعبئة وتجهيز حاصلات زراعية', phoneNumber: '01012299817' },
  { id: '20', supplierName: 'الفتح للتجارة الدولية', address: 'بلبيس - الشرقية', governorate: 'Sharqia', activityType: 'محطة تعبئة وتجهيز حاصلات زراعية', phoneNumber: '01008552601' },
  { id: '21', supplierName: 'الفتح لفرز وتعبئة الحاصلات الزراعية', address: 'بلبيس - المنطقة الصناعية', governorate: 'Sharqia', activityType: 'محطة تعبئة خضار وفاكهة طازجة', phoneNumber: '0553200771' },
  { id: '22', supplierName: 'الفيروز للتصدير والاستيراد', address: 'المنطقة الصناعية - بلبيس - الشرقية', governorate: 'Sharqia', activityType: 'محطة تعبئة وتجهيز حاصلات زراعية', phoneNumber: '01207671666' },
  { id: '23', supplierName: 'القصص للتجارة والتوزيع', address: 'المنطقة الصناعية - بلبيس', governorate: 'Sharqia', activityType: 'محطة تعبئة خضار وفاكهة طازجة', phoneNumber: '0553203727' },
  { id: '24', supplierName: 'الكرم للتنمية والاستثمار الزراعي', address: 'المنطقة الصناعية - بلبيس - الشرقية', governorate: 'Sharqia', activityType: 'محطة تعبئة وتجهيز حاصلات زراعية', phoneNumber: '01207671666' },
  { id: '25', supplierName: 'المحمدي لفرز وتعبئة وتصدير الحاصلات الزراعية', address: 'الكيلو 71 طريق مصر اسكندرية الصحراوي', governorate: 'Beheira', activityType: 'محطة تعبئة خضار وفاكهة طازجة', phoneNumber: '01069209818' },
  { id: '26', supplierName: 'المصرية الالمانية اجابي', address: 'الكيلو 82.5 طريق مصر اسكندرية الصحراوي', governorate: 'Beheira', activityType: 'محطة تعبئة وتجهيز حاصلات زراعية', phoneNumber: '01066811051' },
  { id: '27', supplierName: 'المصرية لتصدير وتجميد الحاصلات الزراعية', address: 'طريق مصر اسكندرية الصحراوي - الكيلو 110', governorate: 'Beheira', activityType: 'محطة تعبئة خضار وفاكهة طازجة', phoneNumber: '01152570087' },
  { id: '28', supplierName: 'النصر لتصدير الحاصلات الزراعية', address: 'الاسكندرية - العامرية', governorate: 'Alexandria', activityType: 'محطة تعبئة وتجهيز حاصلات زراعية', phoneNumber: '01221737025' },
  { id: '29', supplierName: 'النيل للتنمية الزراعية', address: 'الكيلو 71 طريق مصر اسكندرية الصحراوي - مركز بدر - البحيرة', governorate: 'Beheira', activityType: 'محطة تعبئة وتجهيز حاصلات زراعية', phoneNumber: '01277447644' },
  { id: '30', supplierName: 'الوفاء لتصدير الحاصلات الزراعية', address: 'الكيلو 76 طريق القاهرة الاسكندرية الصحراوي', governorate: 'Beheira', activityType: 'محطة تعبئة وتجهيز حاصلات زراعية', phoneNumber: '01006691126' },
  { id: '31', supplierName: 'ام القرى للتنمية الزراعية', address: 'الدقهلية - بلقاس - طريق المعصرة', governorate: 'Dakahlia', activityType: 'محطة تعبئة وتجهيز حاصلات زراعية', phoneNumber: '01005530520' },
  { id: '32', supplierName: 'امجاد لفرز وتعبئة وتصدير الحاصلات الزراعية', address: 'الاسماعيلية - فايد - الاسماعيلية الجديدة', governorate: 'Ismailia', activityType: 'محطة تعبئة وتجهيز حاصلات زراعية', phoneNumber: '01002004862' },
  { id: '33', supplierName: 'اوسكار لتصدير الحاصلات الزراعية', address: 'طريق مصر الاسماعيلية الصحراوي - جمعية السلام', governorate: 'Cairo', activityType: 'محطة تعبئة وتجهيز حاصلات زراعية', phoneNumber: '01110200315' },
  { id: '34', supplierName: 'ايجيبت جرين', address: 'الكيلو 84 طريق مصر اسكندرية الصحراوي - البحيرة', governorate: 'Beheira', activityType: 'محطة تعبئة وتجهيز حاصلات زراعية', phoneNumber: '01112826070' },
  { id: '35', supplierName: 'ايجي جاردن للاستثمار الزراعي', address: 'طريق اسكندرية الصحراوي - الكيلو 96 - مركز بدر', governorate: 'Beheira', activityType: 'محطة تعبئة خضار وفاكهة طازجة', phoneNumber: '01094141555' },
  { id: '36', supplierName: 'ايكو فروت', address: 'النوبارية الجديدة - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطة تعبئة وتجهيز حاصلات زراعية', phoneNumber: '01002885557' },
  { id: '37', supplierName: 'جرين ايجيبت', address: 'الكيلو 80 طريق مصر اسكندرية الصحراوي - مركز بدر - البحيرة', governorate: 'Beheira', activityType: 'محطة تعبئة وتجهيز حاصلات زراعية', phoneNumber: '01009610880' },
  { id: '38', supplierName: 'جرين فالي', address: 'طريق مصر اسكندرية الصحراوي - الكيلو 64 - النوبارية', governorate: 'Beheira', activityType: 'محطة تعبئة خضار وفاكهة طازجة', phoneNumber: '01277169557' },
  { id: '39', supplierName: 'جيزة فريش', address: 'المنصورية - الجيزة', governorate: 'Giza', activityType: 'محطة تعبئة وتجهيز حاصلات زراعية', phoneNumber: '01144143225' },
  { id: '40', supplierName: 'حورس ايجيبت للتنمية الزراعية', address: 'الاسكندرية - الكيلو 11 طريق برج العرب', governorate: 'Alexandria', activityType: 'محطة تعبئة خضار وفاكهة طازجة', phoneNumber: '01068839936' },
  { id: '41', supplierName: 'دلتا فروت', address: 'النوبارية', governorate: 'Beheira', activityType: 'محطة تعبئة خضار وفاكهة طازجة', phoneNumber: '01227770738' },
  { id: '42', supplierName: 'رويال فروت', address: 'الجيزة - المنصورية', governorate: 'Giza', activityType: 'محطة تعبئة خضار وفاكهة طازجة', phoneNumber: '0100107727' },
  { id: '43', supplierName: 'رويال للتصدير', address: 'طريق مصر اسكندرية الصحراوي - الكيلو 110', governorate: 'Beheira', activityType: 'محطة تعبئة خضار وفاكهة طازجة', phoneNumber: '01227785280' },
  { id: '44', supplierName: 'سان اكسبورت', address: 'طريق مصر اسكندرية الصحراوي - الكيلو 62', governorate: 'Beheira', activityType: 'محطة تعبئة خضار وفاكهة طازجة', phoneNumber: '01279922760' },
  { id: '45', supplierName: 'ستار فروت', address: 'المنوفية - السادات - المنطقة الصناعية 16', governorate: 'Monufia', activityType: 'محطة تعبئة خضار وفاكهة طازجة', phoneNumber: '01092200204' },
  { id: '46', supplierName: 'فروتينا', address: 'المنوفية - مدينة السادات - المنطقة الصناعية', governorate: 'Monufia', activityType: 'محطة تعبئة وتجهيز حاصلات زراعية', phoneNumber: '01066008014' },
  { id: '47', supplierName: 'فريش لاند', address: 'طريق مصر اسكندرية الصحراوي - الكيلو 72 - مركز بدر - البحيرة', governorate: 'Beheira', activityType: 'محطة تعبئة وتجهيز حاصلات زراعية', phoneNumber: '01005186825' },
  { id: '48', supplierName: 'فريش لاند للتنمية الزراعية', address: 'طريق مصر اسكندرية الصحراوي - الكيلو 58', governorate: 'Beheira', activityType: 'محطة تعبئة خضار وفاكهة طازجة', phoneNumber: '01010275354' },
  { id: '49', supplierName: 'فيرست فروت', address: 'طريق مصر اسكندرية الصحراوي - الكيلو 86', governorate: 'Beheira', activityType: 'محطة تعبئة خضار وفاكهة طازجة', phoneNumber: '01015726600' },
  { id: '50', supplierName: 'فيتا فروت', address: 'الجيزة - المنصورية', governorate: 'Giza', activityType: 'محطة تعبئة وتجهيز حاصلات زراعية', phoneNumber: '01009869492' },
  { id: '51', supplierName: 'فيوتشر اجري', address: 'النوبارية', governorate: 'Beheira', activityType: 'محطة تعبئة خضار وفاكهة طازجة', phoneNumber: '01006270903' },
  { id: '52', supplierName: 'كيميت', address: 'الجيزة - المنصورية', governorate: 'Giza', activityType: 'محطة تعبئة خضار وفاكهة طازجة', phoneNumber: '01006169860' },
  { id: '53', supplierName: 'لورد', address: 'طريق مصر اسكندرية الصحراوي - الكيلو 84', governorate: 'Beheira', activityType: 'محطة تعبئة خضار وفاكهة طازجة', phoneNumber: '01092082881' },
  { id: '54', supplierName: 'لوتس', address: 'طريق مصر اسكندرية الصحراوي - الكيلو 72', governorate: 'Beheira', activityType: 'محطة تعبئة خضار وفاكهة طازجة', phoneNumber: '01002333415' },
  { id: '55', supplierName: 'ماف', address: 'الجيزة - المنصورية', governorate: 'Giza', activityType: 'محطة تعبئة وتجهيز حاصلات زراعية', phoneNumber: '01068776879' },
  { id: '56', supplierName: 'مصر اورجانيك', address: 'مدينة السادات - المنطقة الصناعية', governorate: 'Monufia', activityType: 'محطة تعبئة وتجهيز حاصلات زراعية', phoneNumber: '01004065647' },
  { id: '57', supplierName: 'مصر ايطاليا', address: 'طريق مصر اسكندرية الصحراوي - الكيلو 72 - مركز بدر - البحيرة', governorate: 'Beheira', activityType: 'محطة تعبئة وتجهيز حاصلات زراعية', phoneNumber: '01000956182' },
  { id: '58', supplierName: 'ميريت', address: 'النوبارية الجديدة', governorate: 'Beheira', activityType: 'محطة تعبئة خضار وفاكهة طازجة', phoneNumber: '01211114805' },
  { id: '59', supplierName: 'ميكو تريد', address: 'طريق مصر الاسماعيلية الصحراوي - جمعية السلام', governorate: 'Cairo', activityType: 'محطة تعبئة وتجهيز حاصلات زراعية', phoneNumber: '01009218902' },
  { id: '60', supplierName: 'نايل فروت', address: 'الاسكندرية - الكيلو 36', governorate: 'Alexandria', activityType: 'محطة تعبئة خضار وفاكهة طازجة', phoneNumber: '01007256001' },
  { id: '61', supplierName: 'نيو تريد', address: 'طريق مصر اسكندرية الصحراوي - الكيلو 68', governorate: 'Beheira', activityType: 'محطة تعبئة وتجهيز حاصلات زراعية', phoneNumber: '01008882835' },
  { id: '62', supplierName: 'يوني جرين', address: 'الاسكندرية - الكيلو 59', governorate: 'Alexandria', activityType: 'محطة تعبئة وتجهيز حاصلات زراعية', phoneNumber: '01066653020' },
  { id: '63', supplierName: 'يوني فروت', address: 'الكيلو 54 طريق مصر اسكندرية الصحراوي', governorate: 'Beheira', activityType: 'محطة تعبئة وتجهيز حاصلات زراعية', phoneNumber: '01023434373' },
  { id: '64', supplierName: 'بيكو', address: 'طريق مصر الاسماعيلية الصحراوي - الصالحية الجديدة', governorate: 'Sharqia', activityType: 'محطة تعبئة وتجهيز حاصلات زراعية', phoneNumber: '01006037211' },
  { id: '65', supplierName: 'جرين لاين', address: 'طريق مصر الاسماعيلية الصحراوي - الكيلو 76', governorate: 'Ismailia', activityType: 'محطة تعبئة وتجهيز حاصلات زراعية', phoneNumber: '01003889963' },
  { id: '66', supplierName: 'اجرو جرين', address: 'الكيلو 86 طريق مصر اسكندرية الصحراوى', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01222418158' },
  { id: '67', supplierName: 'اجزا للتنمية الزراعية', address: 'الاسماعيلية الجديدة - فايد', governorate: 'Ismailia', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01003454645' },
  { id: '68', supplierName: 'ا그رينا', address: 'المنطقة الصناعية ببلبيس', governorate: 'Sharqia', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01112403015' },
  { id: '69', supplierName: 'اجريكو', address: 'الخطاطبة', governorate: 'Monufia', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01009828182' },
  { id: '70', supplierName: 'اجريلاند', address: 'الكيلو 102 طريق مصر اسكندرية الصحراوي', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01006420094' },
  { id: '71', supplierName: 'اجرينا', address: 'المنطقة الصناعية - بلبيس', governorate: 'Sharqia', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01001604845' },
  { id: '72', supplierName: 'اجريفام', address: 'الكيلو 75 طريق مصر اسكندرية الصحراوي', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01027007705' },
  { id: '73', supplierName: 'الأفق', address: 'طريق مصر اسكندرية الصحراوي - الكيلو 98/99', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01281280191' },
  { id: '74', supplierName: 'الأهرام', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01022030114' },
  { id: '75', supplierName: 'الأولى', address: 'النوبارية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01020141404' },
  { id: '76', supplierName: 'الإتحاد', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01226442829' },
  { id: '77', supplierName: 'الإسراء', address: 'الكيلو 84 طريق مصر اسكندرية الصحراوي', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01096303552' },
  { id: '78', supplierName: 'الإسراء للتصدير', address: 'الاسكندرية - برج العرب', governorate: 'Alexandria', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01068826613' },
  { id: '79', supplierName: 'الاسكندرية', address: 'الاسكندرية - الكيلو 52', governorate: 'Alexandria', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01273561719' },
  { id: '80', supplierName: 'الإسماعيلية', address: 'طريق مصر الاسماعيلية الصحراوي - الكيلو 105', governorate: 'Ismailia', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01020802086' },
  { id: '81', supplierName: 'البركة', address: 'طريق مصر اسكندرية الصحراوي - الكيلو 102', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01050740456' },
  { id: '82', supplierName: 'البركة أجرو', address: 'طريق مصر اسكندرية الصحراوي - الكيلو 82', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01223331675' },
  { id: '83', supplierName: 'البركة للتصدير', address: 'طريق مصر اسكندرية الصحراوي - الكيلو 87', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01155653243' },
  { id: '84', supplierName: 'التقوى', address: 'طريق مصر الاسماعيلية الصحراوي - الكيلو 68', governorate: 'Ismailia', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01003641491' },
  { id: '85', supplierName: 'التقوى لفرز وتعبئة الحاصلات', address: 'طريق مصر الاسماعيلية الصحراوي - الكيلو 76', governorate: 'Ismailia', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01020116886' },
  { id: '86', supplierName: 'التوفيق', address: 'النوبارية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01222147201' },
  { id: '87', supplierName: 'التوفيق للتصدير', address: 'الاسكندرية - الكيلو 76', governorate: 'Alexandria', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01220060601' },
  { id: '88', supplierName: 'الجيزة', address: 'المنصورية - الجيزة', governorate: 'Giza', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01141343836' },
  { id: '89', supplierName: 'الجيزة للتصدير', address: 'المنصورية - الجيزة', governorate: 'Giza', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01096866800' },
  { id: '90', supplierName: 'الخير', address: 'طريق مصر الاسماعيلية الصحراوي - الكيلو 49', governorate: 'Sharqia', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01001953624' },
  { id: '91', supplierName: 'الخير لفرز وتعبئة الحاصلات', address: 'طريق مصر الاسكندرية الصحراوي - الكيلو 82', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01069392665' },
  { id: '92', supplierName: 'الخيرات', address: 'المنطقة الصناعية - بلبيس', governorate: 'Sharqia', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01000264416' },
  { id: '93', supplierName: 'الدانة', address: 'المنطقة الصناعية - بلبيس', governorate: 'Sharqia', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01068345983' },
  { id: '94', supplierName: 'الدولية', address: 'الاسكندرية - الكيلو 36', governorate: 'Alexandria', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01000980626' },
  { id: '95', supplierName: 'الدولية للتصدير', address: 'الاسكندرية - الكيلو 88', governorate: 'Alexandria', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01002502218' },
  { id: '96', supplierName: 'الرابية', address: 'طريق مصر اسكندرية الصحراوي - الكيلو 75', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01005194031' },
  { id: '97', supplierName: 'الرحمة', address: 'النوبارية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01001115980' },
  { id: '98', supplierName: 'الرحمة للتصدير', address: 'النوبارية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01003433887' },
  { id: '99', supplierName: 'الرواد', address: 'الاسكندرية - الكيلو 36', governorate: 'Alexandria', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01006055059' },
  { id: '100', supplierName: 'الرواد للتصدير', address: 'طريق مصر اسكندرية الصحراوي - الكيلو 75', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01098569999' },
  { id: '101', supplierName: 'الريان', address: 'الاسكندرية - الكيلو 84', governorate: 'Alexandria', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01222101197' },
  { id: '102', supplierName: 'الزعيم', address: 'الاسكندرية - برج العرب', governorate: 'Alexandria', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01017096878' },
  { id: '103', supplierName: 'الزيني', address: 'الاسكندرية - الكيلو 71', governorate: 'Alexandria', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01001812318' },
  { id: '104', supplierName: 'السلام', address: 'النوبارية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01069877760' },
  { id: '105', supplierName: 'الشناوي', address: 'المنصورة - الدقهلية', governorate: 'Dakahlia', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01119394444' },
  { id: '106', supplierName: 'الشيماء', address: 'المنصورة - الدقهلية', governorate: 'Dakahlia', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01120488775' },
  { id: '107', supplierName: 'الصعيدي', address: 'النوبارية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01205111633' },
  { id: '108', supplierName: 'الصفا', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01222763080' },
  { id: '109', supplierName: 'الصفا للتصدير', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01201959198' },
  { id: '110', supplierName: 'العالمية', address: 'المنصورة - الدقهلية', governorate: 'Dakahlia', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01145004082' },
  { id: '111', supplierName: 'العالمية للتصدير', address: 'الاسكندرية - الكيلو 34', governorate: 'Alexandria', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01013063460' },
  { id: '112', supplierName: 'العربي', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01002650265' },
  { id: '113', supplierName: 'العربي للتصدير', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01093020782' },
  { id: '114', supplierName: 'العزيز', address: 'طريق مصر اسكندرية الصحراوي - الكيلو 87', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01001311325' },
  { id: '115', supplierName: 'العزيزية', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01111705703' },
  { id: '116', supplierName: 'العطار', address: 'النوبارية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01005044574' },
  { id: '117', supplierName: 'الفؤاد', address: 'النوبارية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01066061919' },
  { id: '118', supplierName: 'الفارس', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01202022045' },
  { id: '119', supplierName: 'الفجر', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01000973757' },
  { id: '120', supplierName: 'الفيروز', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01000007055' },
  { id: '121', supplierName: 'الفيوم', address: 'الفيوم - المنطقة الصناعية 20', governorate: 'Faiyum', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01125555209' },
  { id: '122', supplierName: 'القصيم', address: 'طريق مصر اسكندرية الصحراوي - الكيلو 137', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01144445629' },
  { id: '123', supplierName: 'الكامل', address: 'الاسكندرية - الكيلو 98/99', governorate: 'Alexandria', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01010831610' },
  { id: '124', supplierName: 'المتحدة', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01028512777' },
  { id: '125', supplierName: 'المتحدة للتصدير', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01097694000' },
  { id: '126', supplierName: 'المجد', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01103891600' },
  { id: '127', supplierName: 'المحمدية', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01005859549' },
  { id: '128', supplierName: 'المدينة', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01097000883' },
  { id: '129', supplierName: 'المصرية', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01223127929' },
  { id: '130', supplierName: 'المصرية للتصدير', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01097000883' },
  { id: '131', supplierName: 'المصرية الألمانية', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01000922315' },
  { id: '132', supplierName: 'المغربي', address: 'النوبارية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01005787613' },
  { id: '133', supplierName: 'المنصور', address: 'النوبارية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01007191193' },
  { id: '134', supplierName: 'المنوفية', address: 'مدينة السادات - المنطقة الصناعية', governorate: 'Monufia', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01005505020' },
  { id: '135', supplierName: 'المهدي', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01022343421' },
  { id: '136', supplierName: 'الموده', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01289853203' },
  { id: '137', supplierName: 'الميزان', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01017591027' },
  { id: '138', supplierName: 'النور', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01060110176' },
  { id: '139', supplierName: 'النور للتصدير', address: 'الاسكندرية - الكيلو 59', governorate: 'Alexandria', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01210060076' },
  { id: '140', supplierName: 'الوادي', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01285684848' },
  { id: '141', supplierName: 'الوادي الجديد', address: 'النوبارية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01016174816' },
  { id: '142', supplierName: 'امكو', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01289582819' },
  { id: '143', supplierName: 'اورجانيك', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01124320489' },
  { id: '144', supplierName: 'ايجي فارم', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01012674239' },
  { id: '145', supplierName: 'ايجي فروت', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01101281327' },
  { id: '146', supplierName: 'ايكو', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01226502550' },
  { id: '147', supplierName: 'بريمير', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01028572532' },
  { id: '148', supplierName: 'بساتين', address: 'طريق مصر الاسماعيلية الصحراوي - جمعية السلام', governorate: 'Cairo', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01001248696' },
  { id: '149', supplierName: 'بلانت', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01010986412' },
  { id: '150', supplierName: 'توب فروت', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01221722900' },
  { id: '151', supplierName: 'جاردينيا', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01005571003' },
  { id: '152', supplierName: 'جرين', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01009332246' },
  { id: '153', supplierName: 'جرين لاند', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01220770404' },
  { id: '154', supplierName: 'جرين هاوس', address: 'النوبارية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01099923415' },
  { id: '155', supplierName: 'جيزة', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01278855858' },
  { id: '156', supplierName: 'حورس', address: 'طريق مصر الاسماعيلية الصحراوي - الكيلو 44', governorate: 'Sharqia', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01001891212' },
  { id: '157', supplierName: 'حورس للتصدير', address: 'طريق مصر الاسماعيلية الصحراوي - الكيلو 44', governorate: 'Sharqia', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01005645654' },
  { id: '158', supplierName: 'دريم', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01025551980' },
  { id: '159', supplierName: 'دلتا', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01010144120' },
  { id: '160', supplierName: 'روتس', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '233840187' },
  { id: '161', supplierName: 'رويال', address: 'طريق مصر اسكندرية الصحراوي - الكيلو 85 , 86 , 87', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01014676021' },
  { id: '162', supplierName: 'ريم', address: 'النوبارية - بجوار المنطقة الصناعية', governorate: 'Beheira', activityType: 'محطات تعبئه وتجهيز الخضر والفاكهه الطازجه', phoneNumber: '01273760309' }
];
